version: "3"
services:
  latest:
    build:
      context: .
    image: uniwuezpd/ocr4all_base:latest
  staging:
    build:
      context: .
    image: uniwuezpd/ocr4all_base:staging
  dev:
    build:
      context: .
    image: uniwuezpd/ocr4all_base:dev
